before:
    hooks:
        - go mod tidy

builds:
    -
        id: xurlfind3r-cli
        main: cmd/xurlfind3r/main.go
        binary: xurlfind3r

        env:
            - CGO_ENABLED=0

        goos:
            - linux
            - windows
            - darwin
        goarch:
            - amd64
            - 386
            - arm
            - arm64
        ignore:
            - 
                goos: darwin
                goarch: 386
            -
                goos: windows
                goarch: arm
            - 
                goos: windows
                goarch: arm64

        flags:
            - -trimpath

archives:
    -
        id: tgz
        builds: [xurlfind3r-cli]
        format: tar.gz
        replacements:
            darwin: macOS
        format_overrides:
            -
                goos: windows
                format: zip

checksum:
    algorithm: sha256

announce:
    slack:
        enabled: true
        channel: '#release'
        username: GoReleaser
        message_template: 'New Release: {{ .ProjectName }} {{.Tag}} is published! Check it out at {{ .ReleaseURL }}'

    discord:
        enabled: true
        message_template: '**New Release: {{ .ProjectName }} {{.Tag}}** is published! Check it out at {{ .ReleaseURL }}'